### ISSUE TITLE
metalsmith dependency causes Fatal error: Object #<Metalsmith> has no method 'path'

### ISSUE THREAD

**Issue by bsr203** [doingweb/grunt-metalsmith#3]
Hello,

With the latest metalsmith, I get his error.

```
Fatal error: Object #<Metalsmith> has no method 'path'
```

this was reported here https://github.com/segmentio/metalsmith-templates/issues/29

this has been hence fixed in `metalsmith-templates` and `metalsmith (1.0.1)`, but since `grunt-metalsmith` uses an old version 

```
"dependencies": {
    "metalsmith": "^0.11.0"
  }
```

I get that error.

I am not a node/grunt expert, but deleting the `node_modules` of `grunt-metalsmith` solved the issues (so it takes global latest version). not sure how better to solve this.

can't `grunt-metalsmith` takes the version specified in my `package.json` ? or can it remove `metalsmith` from dependency as it always installed?

**Comment by doingweb** [comment]
Thanks for the report!

I'm not sure how to reproduce this error, but it sounds like it'll go away with an update to the Metalsmith dependency. Since there's at least a couple of others interested in that, let's focus our efforts on #2 and get up to 1.x.
